name: kelemapp
description: le kelemu
version: 1.0.2+3

# Environment
environment:
  sdk: ">=2.1.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  flutter_spinkit: ^2.1.0
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0+1"
  google_sign_in: "^4.5.1"
  firebase_core: "^0.7.0"
  firebase_storage: "^7.0.0"
  material_tag_editor: ^0.0.1
  firebase_analytics: ^5.0.15
  rxdart: ^0.20.0
  flutter_signin_button: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.6
  dio: ^3.0.8
  equatable: ^1.2.5
  bloc: ^7.0.0
  flutter_bloc:
  connectivity_plus: ^0.5.0
  image_picker: ^0.6.7+22
  uuid: ^2.2.2
  awesome_dialog: ^2.1.0
# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter assets
flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome/screen1.png
    - assets/images/welcome/screen2.png
    - assets/images/welcome/screen3.png
    - assets/images/addisababa_silhouet.png
    - assets/images/icon_primary_color.png
    - assets/images/reliable.png
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700