name: kelemapp
description: le kelemu
version: 1.0.0+1

# Environment
environment:
  sdk: ">=2.1.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  flutter_spinkit: ^2.1.0
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^3.2.4
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  rxdart: ^0.20.0
  flutter_signin_button: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.6
  connectivity: ^0.4.6+2
  dio: ^3.0.8

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter assets
flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome/screen1.png
    - assets/images/welcome/screen2.png
    - assets/images/welcome/screen3.png
    - assets/images/addisababa_silhouet.png
    - assets/images/icon_primary_color.png
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700